[build]
  command = "composer install && npm install && npm run build"
  publish = "public"
  base = "ecom"

[build.environment]
  PHP_VERSION = "8.2"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200 